---
title: "etiquetas experimentales"
format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    self-contained: true
    output-file: "code"
editor_options: 
  chunk_output_type: console
execute: 
  echo: true
  message: false
  warning: false
---

# Setup

```{r}
#| label: setup

source("https://inkaverse.com/setup.r")
cat("Project: ", getwd(), "\n")
session_info()

# browseURL("https://github.com/Flavjack/untrm_genebank")
```

## Field-book

```{r}
gs <- "https://docs.google.com/spreadsheets/d/1APoUsK8k7n8oSHP9dZXcmpYpJ4a6eJs3QikAp_eOvLQ/edit?gid=537863656#gid=537863656" %>% 
  as_sheets_id()

fb <- gs %>% 
  range_read(ss = .,sheet = "fb")


```

## Labels 

```{r}
#| eval: false

font <- c("Merriweather Sans", "Permanent Marker", "Tillana")

huito_fonts(font)

label <- fb %>%
  arrange(dosis, variedad, .by_group = TRUE) %>% # ordenar por variedad y dosis
  label_layout(size = c(5.2, 10)
               , border_color = "forestgreen"
               , border_width = 1.5
               ) %>%
  include_image(
    value = "https://www.untrm.edu.pe/assets/images/untrmazul.png"
    , size = c(3, 3)
    , position = c(1.6, 9.5)
    ) %>% 
  include_image(
    value = "https://huito.inkaverse.com/img/scale.pdf"
    , size = c(5, 1)
    , position = c(2.6, 8.5)
    ) %>% 
  include_barcode(
    value = "qrcode"
    , size = c(5, 5)
    , position = c(2.6, 5.5)
    ) %>% 
  include_text(value = "plots"
               , position = c(4.5, 9.5)
               , size = 16
               , color = "black"
               , font[1]
               ) %>% 
  include_text(value = "specie"
               , position = c(2.6, 2.6)
               , size = 16
               , color = "blue"
               , font[3]
               ) %>% 
  include_text(value = "led"
               , position = c(2.6, 1.9)
               , size = 15
               , color = "red"
               , font[1]
               ) %>% 
  include_image(
    value = "https://huito.inkaverse.com/img/scale.pdf"
    , size = c(5, 1)
    , position = c(2.6, 0.9)
    ) 

label %>% label_print()
```

```{r}
#| eval: false

label %>% 
  label_print(mode = "c"
              , filename = "etiquetas"
              , paper = c(21.0, 29.7)
              )
```

